apiVersion: v1
kind: Secret
metadata:
  name: "secrets-$k8sapplicationname"
  namespace: "$k8snamespace"
type: Opaque
data:
  MONGO_PASS: "$k8smongopass"
  REDIS_PASSWORD: "$k8sredispassword"
  SQLSERVER_PASSWORD: "$k8ssqlserverpwd"
  API_SECRET: "$k8sjwtpwd"